management:
  endpoint:
    health:
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: example